collections:
  authors:
    output: true
  priorities:
    output: true

defaults:
- scope:
      path: ""
      type: "priorities"
    values:
      layout: "priority"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag