collections:
  authors:
    output: true
  priorities:
    output: true

defaults:
  - scope:
      path: ""
      type: "priorities"
    values:
      layout: "priority"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

social:
  name: Dan Petrow
  links:
    - https://twitter.com/danpetrow
    - https://www.linkedin.com/in/danpetrow
    - https://github.com/danpetrow

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag